import { getLifeStage } from "../../engine/stage";
import type { Choice, Effect, LifeEvent, LifeStage, StatKey } from "../../engine/types";

const stat = (key: StatKey, delta: number): Effect => ({
  type: "stat",
  stat: key,
  delta,
});

const tag = (name: string): Effect => ({
  type: "tag",
  tag: name,
  action: "add",
});

const milestone = (name: string): Effect => ({
  type: "milestone",
  milestone: name,
});

const years = (_value: number): Effect => ({ type: "advanceTime", years: 1 });
const end = (endingId: string): Effect => ({ type: "triggerEnding", endingId });

const stageAnnualTitles: Record<LifeStage, string> = {
  baby: "襁褓余声",
  child: "院墙与课本",
  teen: "分数与风",
  adult: "城中微澜",
  middle: "旧账新债",
  elder: "暮色长明",
};

const annualBodies: Record<LifeStage, string[]> = {
  baby: [
    "这一年，你还不懂命是什么，只记得灯光、手心和忽远忽近的哭声。大人替你做决定，命也替你把路往前推了一寸。",
    "这一年，家里人的语气比天气更能决定你的世界。你学会用哭声回应饥饿，也学会在安静里等人靠近。",
    "这一年，你在许多怀抱之间长大。有人说小孩子没有记忆，可命运已经把温度和缺口都记在了身上。",
  ],
  child: [
    "这一年，作业本、巷口和饭桌上的话一起长进你的身体。你以为自己在挑选爱好，其实很多门已经先替你开了或关了。",
    "这一年，你开始知道比较。别人的新书包、自己的旧铅笔、老师的一句夸奖，都像小石子落进命里的水面。",
    "这一年，童年没有大事，却有许多小小的偏向。你朝某个人靠近，离另一条路远了一点。",
  ],
  teen: [
    "这一年，分数像一把尺，量你，也量你的家。你努力把未来握紧，可命运总从指缝里漏出几粒沙。",
    "这一年，你开始和自己较劲。喜欢、羞耻、野心和恐惧挤在同一张课桌上，谁也不肯先让座。",
    "这一年，很多话没有说出口。它们沉下去，变成日后某次选择时忽然冒出的念头。",
  ],
  adult: [
    "这一年，你在城市的缝隙里赶路。工资、房租、人情和身体轮流催促，你以为是在选择，其实是在偿还前面的命数。",
    "这一年，机会来得不响，压力走得也不响。你把许多委屈折起来收好，像收一张暂时还不能兑现的票。",
    "这一年，世界线轻轻偏了一下。没有人宣布改变，可你已经站在另一种生活的入口边。",
  ],
  middle: [
    "这一年，旧账开始有回声。身体、家庭、事业和未完成的愿望一起坐到桌前，等你给一个交代。",
    "这一年，你更少谈梦想，更多计算风险。命运不再像门外的风，倒像屋里的钟，一声一声催人。",
    "这一年，你发现许多选择不是为了赢，只是为了不让某些东西继续塌下去。",
  ],
  elder: [
    "这一年，日子慢下来，许多往事却走得更近。你回看一生，才发现有些岔路从来不是自己修的。",
    "这一年，你把名字、旧物和几句叮嘱留给后来的人。命运收走力气，也留下回声。",
    "这一年，风从窗边过去。你不再急着证明什么，只偶尔想起当年若是另一场雨，人生会不会不同。",
  ],
};

const annualBaseEffects = (stage: LifeStage): Effect[] => {
  const effectsByStage: Record<LifeStage, Effect[]> = {
    baby: [stat("family", 1), stat("stress", 1)],
    child: [stat("education", 2), stat("relationships", 1), stat("stress", 1)],
    teen: [stat("education", 2), stat("mindset", -1), stat("stress", 2)],
    adult: [stat("career", 2), stat("wealth", 1), stat("health", -1), stat("stress", 2)],
    middle: [stat("family", 1), stat("career", 1), stat("health", -2), stat("stress", 1)],
    elder: [stat("mindset", 1), stat("family", 1), stat("health", -2), stat("reputation", 1)],
  };

  return [...effectsByStage[stage], tag("ordinary_years_accumulated"), years(1)];
};

const annualWeatherTexts: Record<LifeStage, string[]> = {
  baby: ["在潮湿的夜里被抱紧", "在晴窗下睡过一个午后"],
  child: ["冒雨跑过操场", "在大风天守住作业本"],
  teen: ["在闷热晚风里继续赶路", "在忽冷忽热的季节里熬过考试"],
  adult: ["顶着突来的雨去办事", "在晴天里多走一站路"],
  middle: ["在寒潮里照常奔波", "在暴雨前赶回家"],
  elder: ["靠窗等一场雨停", "在难得的好天气里出门走走"],
};

const annualSceneTexts: Record<LifeStage, string[]> = {
  baby: ["被推到巷口晒太阳", "听见楼下人声慢慢远去"],
  child: ["在小卖部门口停了一会儿", "绕到操场边看别人比赛"],
  teen: ["从学校后门绕路回家", "在车站等一班迟到的车"],
  adult: ["在地铁口改了路线", "走进一间陌生的小店"],
  middle: ["在医院走廊坐了半小时", "在社区公告栏前停下"],
  elder: ["在旧街口认了很久路", "坐在公园长椅上看人来人往"],
};

const annualEraTexts: Record<LifeStage, string[]> = {
  baby: ["家里听见一条远处的大新闻", "大人们在饭桌边谈起新的规矩"],
  child: ["学校换了新的通知", "街口开始修一条新路"],
  teen: ["一项政策改变了身边人的打算", "新的风潮吹进了班级"],
  adult: ["公司跟着行业风向调整", "城市出台一条新规定"],
  middle: ["社区和行业同时换了节奏", "一场公共事件改变了安排"],
  elder: ["旧城更新的公告贴了出来", "窗口政策又改了一次"],
};

const annualFateTexts: Record<LifeStage, string[]> = {
  baby: ["错过一次小小的磕碰", "被一个陌生人逗笑"],
  child: ["捡到一枚旧硬币", "因为绕路认识一个朋友"],
  teen: ["迟到一分钟，却避开一场尴尬", "误拿的本子改变了心情"],
  adult: ["错过一班车，遇见另一个机会", "一通电话让计划转了弯"],
  middle: ["临时改约，避开一场麻烦", "一句闲话让你重新盘算"],
  elder: ["忘带钥匙，却多晒了一会儿太阳", "旧人忽然在消息里出现"],
};

const weatherTags = [
  "weather_soft_rain",
  "weather_clear_sun",
  "weather_hard_wind",
  "weather_sudden_cold",
];

const sceneTags = [
  "scene_neighborhood_corner",
  "scene_school_yard",
  "scene_station_platform",
  "scene_hospital_corridor",
  "scene_old_street",
];

const eraTags = [
  "era_policy_notice",
  "era_city_rebuild",
  "era_market_shift",
  "era_public_event",
];

const fateTags = [
  "fate_late_bus",
  "fate_wrong_turn",
  "fate_unexpected_help",
  "fate_missed_signal",
];

function pickAnnualText(texts: Record<LifeStage, string[]>, stage: LifeStage, age: number) {
  const options = texts[stage];
  return options[age % options.length];
}

function annualChoiceSet(stage: LifeStage, age: number): Choice[] {
  const weatherTag = weatherTags[age % weatherTags.length];
  const sceneTag = sceneTags[age % sceneTags.length];
  const eraTag = eraTags[age % eraTags.length];
  const fateTag = fateTags[age % fateTags.length];

  return [
    {
      id: "weather_turn",
      text: pickAnnualText(annualWeatherTexts, stage, age),
      effects: [
        ...annualBaseEffects(stage),
        stat("health", weatherTag === "weather_sudden_cold" ? -2 : 1),
        stat("mindset", weatherTag === "weather_clear_sun" ? 2 : 0),
        tag(weatherTag),
      ],
    },
    {
      id: "scene_detour",
      text: pickAnnualText(annualSceneTexts, stage, age),
      effects: [
        ...annualBaseEffects(stage),
        stat("relationships", 2),
        stat("stress", sceneTag === "scene_hospital_corridor" ? 2 : -1),
        tag(sceneTag),
      ],
    },
    {
      id: "era_ripple",
      text: pickAnnualText(annualEraTexts, stage, age),
      effects: [
        ...annualBaseEffects(stage),
        stat("career", stage === "adult" || stage === "middle" ? 2 : 0),
        stat("risk", eraTag === "era_public_event" ? 2 : 1),
        stat("stress", 2),
        tag(eraTag),
      ],
    },
    {
      id: "fate_small_shift",
      text: pickAnnualText(annualFateTexts, stage, age),
      effects: [
        ...annualBaseEffects(stage),
        stat("luck", fateTag === "fate_unexpected_help" ? 3 : 1),
        stat("mindset", 2),
        tag(fateTag),
      ],
    },
  ];
}

const annualFallbackEvents: LifeEvent[] = Array.from(
  { length: 89 },
  (_, index) => {
    const age = index + 1;
    const stage = getLifeStage(age);
    const bodies = annualBodies[stage];

    return {
      id: `annual_year_${age}`,
      stage,
      title: `${age}岁：${stageAnnualTitles[stage]}`,
      body: bodies[age % bodies.length],
      trigger: { minAge: age, maxAge: age },
      weight: 1,
      fallback: true,
      choices: annualChoiceSet(stage, age),
    };
  },
);

const everydayLifeEvents: LifeEvent[] = [
  {
    id: "study_teacher_sentence",
    stage: "child",
    title: "一位老师",
    body: "有位老师在作业本边上写了一句很短的话。你那时不知道，一句话也能在人心里住很多年。",
    trigger: { minAge: 8, maxAge: 12 },
    weight: 18,
    once: true,
    choices: [
      {
        id: "believe_teacher",
        text: "相信自己也能学好",
        effects: [
          stat("education", 7),
          stat("intelligence", 3),
          stat("mindset", 4),
          tag("study_encouraged"),
          milestone("teacher_sentence_kept"),
          years(1),
        ],
      },
      {
        id: "fear_teacher",
        text: "开始害怕被点名",
        effects: [
          stat("education", 3),
          stat("stress", 5),
          stat("mindset", -3),
          tag("study_anxious"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "study_library_light",
    stage: "teen",
    title: "自习室的灯",
    body: "晚自习结束后，楼道的灯一盏盏灭下去。你留下来写最后一道题，像是在和看不见的出身较劲。",
    trigger: { minAge: 13, maxAge: 18 },
    weight: 20,
    once: true,
    choices: [
      {
        id: "burn_late_for_books",
        text: "把夜晚交给书页",
        effects: [
          stat("education", 9),
          stat("intelligence", 5),
          stat("stress", 6),
          stat("health", -2),
          tag("study_grit"),
          tag("world_learning_track"),
          milestone("burned_late_library"),
          years(1),
        ],
      },
      {
        id: "protect_sleep",
        text: "保住睡眠和朋友",
        effects: [
          stat("health", 5),
          stat("relationships", 4),
          stat("mindset", 4),
          stat("education", 3),
          tag("study_balanced"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "study_exam_resit",
    stage: "teen",
    title: "重考的门",
    body: "成绩出来那天，你坐在楼梯间很久。重新来一年像把青春往回折，往前走又像承认那扇门已经关上。",
    trigger: { minAge: 17, maxAge: 19 },
    weight: 18,
    once: true,
    choices: [
      {
        id: "try_resit",
        text: "再给自己一年",
        effects: [
          stat("education", 10),
          stat("stress", 8),
          stat("mindset", 2),
          tag("study_second_chance"),
          milestone("stood_before_exam_again"),
          years(1),
        ],
      },
      {
        id: "leave_exam",
        text: "带着不甘往前走",
        effects: [
          stat("career", 3),
          stat("relationships", 2),
          stat("mindset", -2),
          tag("study_unfinished"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "study_major_mismatch",
    stage: "adult",
    title: "不合身的专业",
    body: "你坐在专业课教室里，听着别人热烈讨论，忽然觉得自己像穿了一件不合身的衣服。可换路从来不是只换一张课表。",
    trigger: { minAge: 18, maxAge: 24 },
    weight: 16,
    once: true,
    choices: [
      {
        id: "change_major_path",
        text: "冒险换到想去的方向",
        effects: [
          stat("education", 6),
          stat("mindset", 6),
          stat("risk", 4),
          tag("study_changed_path"),
          tag("world_side_path"),
          years(1),
        ],
      },
      {
        id: "finish_major_anyway",
        text: "先把证书拿到手",
        effects: [
          stat("education", 7),
          stat("career", 2),
          stat("stress", 4),
          tag("study_pragmatic"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "love_first_confession",
    stage: "teen",
    title: "第一封消息",
    body: "你在输入框里打了又删。喜欢一个人时，发送键像一座桥，也像一条河。",
    trigger: { minAge: 15, maxAge: 18 },
    weight: 18,
    once: true,
    choices: [
      {
        id: "send_confession",
        text: "把心意发出去",
        effects: [
          stat("relationships", 6),
          stat("charm", 3),
          stat("mindset", 3),
          tag("love_brave_first"),
          milestone("first_heart_sent"),
          years(1),
        ],
      },
      {
        id: "save_confession",
        text: "把消息存成草稿",
        effects: [
          stat("mindset", -2),
          stat("charm", 2),
          tag("love_unsent_message"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "love_long_distance",
    stage: "adult",
    title: "两座城市",
    body: "你们在不同城市醒来，又在同一个深夜通话。距离把爱拉长，也把很多现实问题拉到眼前。",
    trigger: { minAge: 19, maxAge: 30 },
    weight: 16,
    once: true,
    choices: [
      {
        id: "keep_long_distance",
        text: "认真维系这段关系",
        effects: [
          stat("relationships", 8),
          stat("stress", 5),
          stat("mindset", 2),
          tag("love_long_distance_kept"),
          milestone("kept_two_city_love"),
          years(1),
        ],
      },
      {
        id: "end_long_distance",
        text: "体面地放手",
        effects: [
          stat("mindset", -3),
          stat("career", 3),
          stat("relationships", -2),
          tag("love_let_go"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "love_marriage_table",
    stage: "adult",
    title: "谈婚论嫁的桌子",
    body: "两家人坐在一张桌边，爱忽然变成了城市、彩礼、房子、老人和未来孩子的预算。",
    trigger: { minAge: 24, maxAge: 36 },
    weight: 17,
    once: true,
    choices: [
      {
        id: "build_marriage",
        text: "把日子一起扛起来",
        effects: [
          stat("family", 8),
          stat("relationships", 5),
          stat("wealth", -5),
          stat("stress", 4),
          tag("love_built_home"),
          tag("built_family"),
          years(1),
        ],
      },
      {
        id: "delay_marriage",
        text: "先把各自站稳",
        effects: [
          stat("career", 5),
          stat("mindset", 3),
          stat("relationships", -3),
          tag("love_delayed_marriage"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "love_quiet_partnership",
    stage: "middle",
    title: "沉默的同盟",
    body: "很多年后，爱情不常说出口。它变成谁去缴费、谁记得吃药、谁在夜里等另一个人回家。",
    trigger: { minAge: 40, maxAge: 58 },
    weight: 15,
    once: true,
    choices: [
      {
        id: "repair_partnership",
        text: "把沉默重新说开",
        effects: [
          stat("family", 8),
          stat("relationships", 6),
          stat("mindset", 4),
          tag("love_repaired_middle"),
          milestone("middle_years_spoke_again"),
          years(1),
        ],
      },
      {
        id: "live_parallel",
        text: "继续各过各的",
        effects: [
          stat("stress", 3),
          stat("mindset", -3),
          stat("relationships", -5),
          tag("love_parallel_life"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "work_first_overtime",
    stage: "adult",
    title: "第一次通宵加班",
    body: "办公室凌晨两点还亮着。你盯着屏幕，第一次明白所谓职场上升，常常从把身体抵押给明天开始。",
    trigger: { minAge: 20, maxAge: 30 },
    weight: 18,
    once: true,
    choices: [
      {
        id: "take_overtime",
        text: "咬牙把项目做完",
        effects: [
          stat("career", 8),
          stat("reputation", 4),
          stat("health", -4),
          stat("stress", 6),
          tag("work_overtime_mark"),
          milestone("first_all_nighter"),
          years(1),
        ],
      },
      {
        id: "set_work_boundary",
        text: "开始给工作设边界",
        effects: [
          stat("health", 5),
          stat("mindset", 4),
          stat("career", 2),
          tag("work_boundary_set"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "work_bad_boss",
    stage: "adult",
    title: "坏上司",
    body: "有些人把位置当成武器。你站在工位边，手里拿着方案，心里算着忍耐还能换来什么。",
    trigger: { minAge: 22, maxAge: 38 },
    weight: 16,
    once: true,
    choices: [
      {
        id: "endure_bad_boss",
        text: "先忍，攒资历",
        effects: [
          stat("career", 5),
          stat("stress", 8),
          stat("mindset", -3),
          tag("work_swallowed_grievance"),
          years(1),
        ],
      },
      {
        id: "leave_bad_boss",
        text: "把辞职信写完",
        effects: [
          stat("mindset", 6),
          stat("risk", 5),
          stat("career", -2),
          tag("work_left_bad_boss"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "work_small_promotion",
    stage: "adult",
    title: "小小晋升",
    body: "邮件里只有几行字，工资多了一点，责任多了很多。你笑了一下，又很快开始回下一封消息。",
    trigger: {
      minAge: 25,
      maxAge: 45,
      conditions: [{ type: "stat", stat: "career", op: ">=", value: 24 }],
    },
    weight: 15,
    once: true,
    choices: [
      {
        id: "take_manager_path",
        text: "接住新的责任",
        effects: [
          stat("career", 8),
          stat("wealth", 4),
          stat("stress", 5),
          tag("work_promoted"),
          milestone("first_promotion_letter"),
          years(1),
        ],
      },
      {
        id: "stay_specialist",
        text: "守住专业节奏",
        effects: [
          stat("career", 5),
          stat("mindset", 4),
          stat("stress", -2),
          tag("work_specialist_path"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "work_layoff_notice",
    stage: "middle",
    title: "优化名单",
    body: "名单没有写在公告里，却先写在了每个人的脸上。你突然发现，一份工作从来不是地基，只是暂时能站的地方。",
    trigger: { minAge: 35, maxAge: 55 },
    weight: 15,
    once: true,
    choices: [
      {
        id: "prepare_layoff",
        text: "提前准备退路",
        effects: [
          stat("career", 3),
          stat("risk", -4),
          stat("stress", 3),
          tag("work_prepared_exit"),
          years(1),
        ],
      },
      {
        id: "ignore_layoff",
        text: "相信名单不会有自己",
        effects: [
          stat("stress", 7),
          stat("wealth", -5),
          stat("mindset", -4),
          tag("work_layoff_hit"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "illness_child_fever",
    stage: "child",
    title: "夜里的高烧",
    body: "半夜，你烧得迷迷糊糊。大人抱着你冲进医院，白灯和消毒水味成了童年里最早的阴影之一。",
    trigger: { minAge: 3, maxAge: 10 },
    weight: 13,
    once: true,
    choices: [
      {
        id: "treated_fever",
        text: "被及时送去医院",
        effects: [
          stat("health", 3),
          stat("family", 4),
          stat("wealth", -2),
          tag("illness_child_survived"),
          years(1),
        ],
      },
      {
        id: "weak_after_fever",
        text: "从此体质弱了一点",
        effects: [
          stat("health", -6),
          stat("risk", 4),
          tag("illness_weak_constitution"),
          milestone("fever_left_shadow"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "illness_chronic_signal",
    stage: "adult",
    title: "慢性指标",
    body: "体检单上有几个数不太好看。医生说现在调整还来得及，你却先想起了今晚还没回完的消息。",
    trigger: { minAge: 28, maxAge: 44 },
    weight: 14,
    once: true,
    choices: [
      {
        id: "change_lifestyle",
        text: "认真调整作息",
        effects: [
          stat("health", 8),
          stat("stress", -3),
          stat("career", -1),
          tag("illness_lifestyle_changed"),
          years(1),
        ],
      },
      {
        id: "delay_lifestyle",
        text: "等忙完这一阵",
        effects: [
          stat("health", -7),
          stat("stress", 4),
          stat("career", 3),
          tag("illness_warning_ignored"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "illness_family_history",
    stage: "middle",
    title: "家族病史",
    body: "医生问起家族病史时，你忽然想起很多长辈的名字。血缘不是只带来姓氏，也带来一些躲不开的风险。",
    trigger: { minAge: 42, maxAge: 62 },
    weight: 13,
    once: true,
    choices: [
      {
        id: "screen_regularly",
        text: "开始规律筛查",
        effects: [
          stat("health", 7),
          stat("wealth", -4),
          stat("risk", -6),
          tag("illness_regular_screening"),
          milestone("family_history_faced"),
          years(1),
        ],
      },
      {
        id: "avoid_screening",
        text: "不想太早面对",
        effects: [
          stat("mindset", -2),
          stat("risk", 7),
          tag("illness_screening_avoided"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "illness_surgery_wait",
    stage: "any",
    title: "手术等候区",
    body: "你坐在手术室外，手机电量一点点掉。人生在这里变得很窄，只剩一扇门、一盏灯和几句反复确认的话。",
    trigger: {
      minAge: 25,
      maxAge: 75,
      conditions: [{ type: "stat", stat: "health", op: "<=", value: 48 }],
    },
    weight: 12,
    once: true,
    choices: [
      {
        id: "trust_doctors",
        text: "把自己交给治疗",
        effects: [
          stat("health", 10),
          stat("wealth", -8),
          stat("mindset", 3),
          tag("illness_surgery_recovered"),
          years(1),
        ],
      },
      {
        id: "fear_surgery",
        text: "在恐惧里反复犹豫",
        effects: [
          stat("health", -4),
          stat("stress", 8),
          stat("family", 2),
          tag("illness_surgery_feared"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "travel_school_trip",
    stage: "teen",
    title: "第一次远足",
    body: "大巴车开出熟悉的街道，你靠着车窗，看见城市外面的河和山。原来世界不只由作业和家门口组成。",
    trigger: { minAge: 12, maxAge: 17 },
    weight: 14,
    once: true,
    choices: [
      {
        id: "open_to_world",
        text: "把远方记在心里",
        effects: [
          stat("mindset", 5),
          stat("relationships", 3),
          stat("charm", 2),
          tag("travel_first_distance"),
          milestone("first_trip_opened_world"),
          years(1),
        ],
      },
      {
        id: "miss_home_on_trip",
        text: "一路想着早点回家",
        effects: [
          stat("family", 3),
          stat("mindset", 1),
          tag("travel_homebound"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "travel_first_train",
    stage: "adult",
    title: "绿皮车夜行",
    body: "火车穿过夜色，车厢里有人吃泡面，有人打呼。你抱着包，第一次觉得远方既便宜又昂贵。",
    trigger: { minAge: 18, maxAge: 28 },
    weight: 14,
    once: true,
    choices: [
      {
        id: "take_train_to_chance",
        text: "坐到终点找机会",
        effects: [
          stat("career", 4),
          stat("mindset", 4),
          stat("risk", 3),
          tag("travel_train_departure"),
          tag("world_departure_signal"),
          years(1),
        ],
      },
      {
        id: "return_from_train",
        text: "中途下车回头",
        effects: [
          stat("family", 4),
          stat("mindset", -1),
          tag("travel_returned_early"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "travel_seaside_pause",
    stage: "adult",
    title: "海边短暂停留",
    body: "你请了两天假去看海。浪一遍遍推上来，又一遍遍退回去，像生活把人逼到边上再放回去。",
    trigger: { minAge: 24, maxAge: 45 },
    weight: 13,
    once: true,
    choices: [
      {
        id: "rest_by_sea",
        text: "认真休息两天",
        effects: [
          stat("health", 5),
          stat("mindset", 7),
          stat("wealth", -3),
          tag("travel_restored_by_sea"),
          milestone("heard_sea_between_years"),
          years(1),
        ],
      },
      {
        id: "work_at_sea",
        text: "边看海边回消息",
        effects: [
          stat("career", 3),
          stat("stress", 4),
          stat("mindset", -1),
          tag("travel_could_not_rest"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "travel_foreign_city",
    stage: "middle",
    title: "陌生城市的清晨",
    body: "你在语言不通的街头买早餐，忽然觉得自己也可以短暂地从原来的身份里走出来。",
    trigger: { minAge: 35, maxAge: 60 },
    weight: 12,
    once: true,
    choices: [
      {
        id: "walk_foreign_city",
        text: "慢慢走完整条街",
        effects: [
          stat("mindset", 6),
          stat("charm", 3),
          stat("wealth", -5),
          tag("travel_foreign_morning"),
          years(1),
        ],
      },
      {
        id: "fear_foreign_city",
        text: "早点回到酒店",
        effects: [
          stat("stress", -1),
          stat("mindset", 1),
          tag("travel_kept_close"),
          years(1),
        ],
      },
    ],
  },
];

const wealthTimelineEvents: LifeEvent[] = [
  {
    id: "wealth_first_paycheck",
    stage: "adult",
    title: "第一笔工资",
    body: "工资到账的清晨，你盯着那串数字看了很久。它不算多，却像一张窄窄的船票，证明你终于能靠自己的双手往前挪一点。旁边也有人递来更快的钱路，没有合同，也没有太多问题。",
    trigger: { minAge: 18, maxAge: 28 },
    weight: 18,
    once: true,
    choices: [
      {
        id: "record_clean_paycheck",
        text: "把第一笔钱清清楚楚记进账本",
        effects: [
          stat("wealth", 8),
          stat("career", 4),
          stat("reputation", 2),
          stat("stress", 2),
          tag("wealth_honest_income"),
          tag("world_honest_ladder"),
          milestone("first_clean_paycheck"),
          years(1),
        ],
      },
      {
        id: "take_cash_shortcut",
        text: "接下那份没有合同的现金活",
        effects: [
          stat("wealth", 12),
          stat("risk", 7),
          stat("stress", 4),
          stat("reputation", -2),
          tag("wealth_cash_shortcut"),
          tag("world_gray_money"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "wealth_side_door_offer",
    stage: "adult",
    title: "侧门邀约",
    body: "旧同学约你在茶馆见面，说最近有个项目，走正规流程太慢，懂的人先吃肉。你听见窗外雨声很密，像有人在替你数未来要还的账。",
    trigger: { minAge: 22, maxAge: 42 },
    weight: 16,
    once: true,
    choices: [
      {
        id: "build_clean_side_job",
        text: "做一份明码标价的副业",
        effects: [
          stat("wealth", 10),
          stat("career", 4),
          stat("stress", 5),
          stat("reputation", 3),
          tag("wealth_clean_side_job"),
          tag("wealth_honest_income"),
          tag("world_honest_ladder"),
          years(1),
        ],
      },
      {
        id: "enter_gray_arbitrage",
        text: "跟着他们做几轮偏门套利",
        effects: [
          stat("wealth", 18),
          stat("risk", 12),
          stat("stress", 8),
          stat("reputation", -4),
          tag("wealth_gray_income"),
          tag("wealth_risk_mark"),
          tag("world_gray_money"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "wealth_tech_degree",
    stage: "adult",
    title: "技术学位",
    body: "夜校、网课、实验室和项目仓库挤满了你的夜晚。有人说学历只是纸，有人说技术才是铁饭碗。你知道这张纸未必改命，但它可能让某扇门愿意多开一秒。",
    trigger: {
      minAge: 18,
      maxAge: 32,
      conditions: [{ type: "stat", stat: "education", op: ">=", value: 30 }],
    },
    weight: 17,
    once: true,
    choices: [
      {
        id: "earn_tech_degree",
        text: "咬牙拿下技术学位",
        effects: [
          stat("education", 9),
          stat("intelligence", 6),
          stat("career", 4),
          stat("wealth", -8),
          stat("stress", 7),
          tag("wealth_tech_degree"),
          tag("wealth_code_skill"),
          tag("world_tech_venture"),
          milestone("tech_degree_earned"),
          years(1),
        ],
      },
      {
        id: "learn_enough_for_job",
        text: "只学够眼前工作要用的本事",
        effects: [
          stat("education", 4),
          stat("career", 5),
          stat("wealth", 2),
          stat("stress", 2),
          tag("wealth_practical_skill"),
          tag("world_honest_ladder"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "wealth_tech_startup",
    stage: "adult",
    title: "产品上线前夜",
    body: "你和合伙人在办公室里守着服务器日志。学位、代码、融资电话和拖欠的房租叠在一起，像一座随时会晃的桥。桥那头可能是公司，也可能只是又一段履历。",
    trigger: {
      minAge: 24,
      maxAge: 45,
      conditions: [
        { type: "tag", tag: "wealth_tech_degree", present: true },
      ],
    },
    weight: 18,
    once: true,
    choices: [
      {
        id: "launch_tech_product",
        text: "把技术做成真正的产品",
        effects: [
          stat("career", 9),
          stat("wealth", 14),
          stat("risk", 10),
          stat("stress", 9),
          stat("reputation", 6),
          tag("wealth_tech_startup"),
          tag("world_tech_venture"),
          milestone("first_product_launched"),
          years(1),
        ],
      },
      {
        id: "sell_technical_consulting",
        text: "先做稳定的技术顾问",
        effects: [
          stat("career", 7),
          stat("wealth", 12),
          stat("stress", 4),
          stat("reputation", 4),
          tag("wealth_technical_consulting"),
          tag("wealth_honest_income"),
          tag("world_honest_ladder"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "wealth_law_exam",
    stage: "adult",
    title: "法律考试",
    body: "你把法条背到深夜，桌上冷掉的茶一杯接一杯。法律像一条干净的线，可线后面站着人情、费用、输赢和许多说不出口的请求。",
    trigger: {
      minAge: 20,
      maxAge: 36,
      conditions: [{ type: "stat", stat: "education", op: ">=", value: 35 }],
    },
    weight: 15,
    once: true,
    choices: [
      {
        id: "pass_law_path",
        text: "把法条背到天亮",
        effects: [
          stat("education", 7),
          stat("career", 5),
          stat("wealth", -5),
          stat("stress", 7),
          stat("reputation", 3),
          tag("wealth_lawyer_path"),
          tag("world_legal_path"),
          milestone("law_exam_passed"),
          years(1),
        ],
      },
      {
        id: "work_as_legal_assistant",
        text: "先去律所做法务助理",
        effects: [
          stat("career", 5),
          stat("wealth", 4),
          stat("stress", 3),
          stat("reputation", 1),
          tag("wealth_legal_assistant"),
          tag("world_legal_path"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "wealth_lawyer_case",
    stage: "any",
    title: "棘手的案子",
    body: "一个案子摆到你面前。委托人带着厚厚一袋材料，也带着一句含糊的暗示：只要能赢，办法可以再想。你听见自己的职业誓言在心里轻轻响了一下。",
    trigger: {
      minAge: 26,
      maxAge: 60,
      conditions: [
        { type: "tag", tag: "wealth_lawyer_path", present: true },
      ],
    },
    weight: 15,
    once: true,
    choices: [
      {
        id: "argue_case_cleanly",
        text: "只用证据和法条打这场仗",
        effects: [
          stat("career", 8),
          stat("wealth", 9),
          stat("reputation", 8),
          stat("stress", 6),
          stat("risk", -3),
          tag("wealth_clean_law_practice"),
          tag("wealth_honest_income"),
          tag("world_legal_path"),
          years(1),
        ],
      },
      {
        id: "bend_case_edges",
        text: "把关系和灰线也算进策略",
        effects: [
          stat("career", 6),
          stat("wealth", 16),
          stat("risk", 12),
          stat("stress", 10),
          stat("reputation", -4),
          tag("wealth_legal_gray_edge"),
          tag("wealth_gray_income"),
          tag("wealth_risk_mark"),
          tag("world_gray_money"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "wealth_tax_line",
    stage: "middle",
    title: "账本边缘",
    body: "收入终于像样了，账本也厚了起来。朋友说有些钱可以藏一藏，规矩总会落后于聪明人。你摸着发票边缘，忽然觉得纸也会割手。",
    trigger: {
      minAge: 35,
      maxAge: 60,
      conditions: [{ type: "stat", stat: "wealth", op: ">=", value: 55 }],
    },
    weight: 14,
    once: true,
    choices: [
      {
        id: "keep_books_clean",
        text: "把账本做得清清楚楚",
        effects: [
          stat("wealth", -5),
          stat("reputation", 5),
          stat("risk", -6),
          stat("stress", -2),
          tag("wealth_clean_books"),
          tag("wealth_honest_income"),
          tag("world_honest_ladder"),
          milestone("clean_books_kept"),
          years(1),
        ],
      },
      {
        id: "hide_part_of_income",
        text: "把一部分收入藏到暗处",
        effects: [
          stat("wealth", 13),
          stat("risk", 13),
          stat("stress", 7),
          stat("reputation", -6),
          tag("wealth_hidden_books"),
          tag("wealth_gray_income"),
          tag("wealth_risk_mark"),
          tag("world_gray_money"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "wealth_windfall_investment",
    stage: "any",
    title: "一笔意外的钱",
    body: "一笔钱突然落到你手里：奖金、赔偿、分红，或者某个早年忘记的小投资。它来得太巧，像命运把一枚硬币放在你掌心，让你误以为自己能决定它下一次朝上是哪面。",
    trigger: {
      minAge: 25,
      maxAge: 65,
      conditions: [{ type: "stat", stat: "wealth", op: ">=", value: 40 }],
    },
    weight: 14,
    once: true,
    choices: [
      {
        id: "choose_compound_interest",
        text: "把钱放进长期复利里",
        effects: [
          stat("wealth", 10),
          stat("mindset", 4),
          stat("risk", -2),
          stat("stress", -1),
          tag("wealth_compound_interest"),
          tag("wealth_honest_income"),
          tag("world_honest_ladder"),
          years(1),
        ],
      },
      {
        id: "take_leveraged_bet",
        text: "押上杠杆赌一把大的",
        effects: [
          stat("wealth", 20),
          stat("luck", -3),
          stat("risk", 15),
          stat("stress", 9),
          tag("wealth_leverage_bet"),
          tag("wealth_risk_mark"),
          tag("world_capital_wind"),
          years(1),
        ],
      },
    ],
  },
];

export const baseEvents: LifeEvent[] = [
  {
    id: "birth_fate_lot",
    stage: "baby",
    title: "命盘初定",
    body: "你出生那天，窗外下着小雨。长辈说孩子哭声亮，命硬；母亲只觉得日子还长。很多东西在你还不会说话时就已经落定，像一条看不见的线，先替你牵住了远处。",
    trigger: { minAge: 0, maxAge: 2 },
    weight: 100,
    once: true,
    milestone: true,
    choices: [
      {
        id: "held_by_many_hands",
        text: "被许多双手稳稳接住",
        effects: [
          stat("family", 10),
          stat("mindset", 6),
          stat("classBackground", 5),
          tag("supportive_family"),
          tag("world_kind_home"),
          milestone("first_luck_was_shelter"),
          years(4),
        ],
      },
      {
        id: "born_between_moves",
        text: "在搬家和欠账声里长大",
        effects: [
          stat("stress", 10),
          stat("luck", 4),
          stat("classBackground", -8),
          tag("rootless_child"),
          tag("world_family_debt"),
          milestone("first_lesson_was_debt"),
          years(4),
        ],
      },
      {
        id: "frail_first_winter",
        text: "熬过一场虚弱的初冬",
        effects: [
          stat("health", -8),
          stat("family", 6),
          stat("risk", 6),
          tag("frail_start"),
          tag("world_body_debt"),
          milestone("first_winter_survived"),
          years(4),
        ],
      },
    ],
  },
  {
    id: "child_hometown_roads",
    stage: "child",
    title: "巷口的路",
    body: "你家门口有两条路。一条通向学校，一条通向车站。你不知道自己以后会反复在这两条路之间做选择。",
    trigger: { minAge: 3, maxAge: 9 },
    weight: 28,
    once: true,
    choices: [
      {
        id: "stay_in_lane",
        text: "沿着熟悉的路去学校",
        effects: [
          stat("education", 8),
          stat("family", 4),
          tag("hometown_tie"),
          tag("world_hometown_gravity"),
          years(3),
        ],
      },
      {
        id: "watch_the_station",
        text: "站在车站边看远方的人",
        effects: [
          stat("mindset", 5),
          stat("charm", 3),
          stat("relationships", -2),
          tag("wanderer_seed"),
          tag("world_departure_signal"),
          years(3),
        ],
      },
    ],
  },
  {
    id: "child_books_or_yard",
    stage: "child",
    title: "书页与院子",
    body: "有些下午适合读书，有些下午适合奔跑。你以为这只是兴趣，后来才知道，人会被童年的注意力牵着走很久。",
    trigger: { minAge: 5, maxAge: 12 },
    weight: 24,
    once: true,
    choices: [
      {
        id: "bookish_child",
        text: "把自己藏进书页里",
        effects: [
          stat("intelligence", 9),
          stat("education", 10),
          stat("relationships", -2),
          tag("bookish_child"),
          milestone("learned_to_hide_in_books"),
          years(3),
        ],
      },
      {
        id: "yard_child",
        text: "跟着孩子们跑遍院子",
        effects: [
          stat("health", 6),
          stat("charm", 6),
          stat("relationships", 7),
          tag("social_child"),
          milestone("learned_to_read_people"),
          years(3),
        ],
      },
    ],
  },
  {
    id: "child_parent_layoff",
    stage: "child",
    title: "饭桌上的沉默",
    body: "某天晚饭，父亲或母亲比平时回来得早。大人们不说发生了什么，但你听懂了碗筷之间的沉默。",
    trigger: { minAge: 7, maxAge: 12 },
    weight: 18,
    once: true,
    choices: [
      {
        id: "become_sensible",
        text: "早早学会懂事",
        effects: [
          stat("stress", 9),
          stat("family", 5),
          stat("mindset", -2),
          tag("early_sensible"),
          tag("world_factory_winter"),
          years(3),
        ],
      },
      {
        id: "pretend_not_to_know",
        text: "假装什么都没听见",
        effects: [
          stat("mindset", 4),
          stat("family", -4),
          stat("relationships", 2),
          tag("avoidant_heart"),
          tag("world_silent_home"),
          years(3),
        ],
      },
    ],
  },
  {
    id: "child_teacher_notice",
    stage: "child",
    title: "被老师点名",
    body: "老师把你的作业拿给全班看。那一刻你分不清是骄傲还是害怕，只觉得命运忽然看了你一眼。",
    trigger: {
      minAge: 8,
      maxAge: 12,
      conditions: [{ type: "stat", stat: "education", op: ">=", value: 8 }],
    },
    weight: 20,
    once: true,
    choices: [
      {
        id: "accept_attention",
        text: "接住这份期待",
        effects: [
          stat("education", 8),
          stat("reputation", 4),
          stat("stress", 4),
          tag("teacher_expectation"),
          tag("world_education_track"),
          years(2),
        ],
      },
      {
        id: "fear_attention",
        text: "开始害怕被看见",
        effects: [
          stat("education", 4),
          stat("mindset", -4),
          stat("stress", 6),
          tag("fear_of_attention"),
          years(2),
        ],
      },
    ],
  },
  {
    id: "teen_exam_machine",
    stage: "teen",
    title: "升学机器",
    body: "排名、补课、志愿表和亲戚的比较挤在一起。所有人都说努力能改命，但没有人说起点不同会让努力变得多重。",
    trigger: { minAge: 13, maxAge: 18 },
    weight: 34,
    once: true,
    milestone: true,
    choices: [
      {
        id: "grind_for_score",
        text: "把自己拧进分数里",
        effects: [
          stat("education", 18),
          stat("stress", 12),
          stat("health", -4),
          tag("exam_focused"),
          tag("world_exam_machine"),
          milestone("burned_for_the_exam"),
          years(4),
        ],
      },
      {
        id: "keep_breathing",
        text: "保住节奏，也保住自己",
        effects: [
          stat("education", 9),
          stat("mindset", 6),
          stat("relationships", 4),
          tag("balanced_teen"),
          years(4),
        ],
      },
      {
        id: "leave_the_track",
        text: "不愿被一张卷子定义",
        effects: [
          stat("charm", 7),
          stat("mindset", 8),
          stat("education", -3),
          stat("risk", 7),
          tag("independent_teen"),
          tag("world_side_path"),
          years(4),
        ],
      },
    ],
  },
  {
    id: "teen_friend_fork",
    stage: "teen",
    title: "同桌的岔路",
    body: "你的同桌忽然退学，去跟亲戚学手艺。你们在校门口分别，谁也不知道哪条路更像出路。",
    trigger: { minAge: 14, maxAge: 18 },
    weight: 16,
    once: true,
    choices: [
      {
        id: "stay_with_books",
        text: "留在课桌前",
        effects: [
          stat("education", 8),
          stat("relationships", -3),
          tag("stayed_on_track"),
          milestone("watched_a_friend_leave"),
          years(2),
        ],
      },
      {
        id: "envy_other_road",
        text: "第一次羡慕另一种活法",
        effects: [
          stat("mindset", 5),
          stat("risk", 5),
          tag("envied_side_road"),
          tag("world_side_path"),
          years(2),
        ],
      },
    ],
  },
  {
    id: "teen_first_love",
    stage: "teen",
    title: "未寄出的信",
    body: "你喜欢上一个人，信写了三遍都没寄出去。青春像一列误点的车，你追不上，也舍不得走。",
    trigger: { minAge: 15, maxAge: 18 },
    weight: 14,
    once: true,
    choices: [
      {
        id: "hide_the_letter",
        text: "把信夹进书里",
        effects: [
          stat("mindset", -2),
          stat("education", 4),
          tag("unspoken_love"),
          milestone("first_unsent_letter"),
          years(2),
        ],
      },
      {
        id: "send_the_letter",
        text: "把信递出去",
        effects: [
          stat("charm", 5),
          stat("relationships", 6),
          stat("stress", 3),
          tag("brave_first_love"),
          years(2),
        ],
      },
    ],
  },
  {
    id: "teen_policy_shift",
    stage: "teen",
    title: "政策风向",
    body: "某年，考试政策和城市招生名额突然调整。你第一次感到，所谓选择，经常只是时代先替你挪了棋盘。",
    trigger: { minAge: 16, maxAge: 19 },
    weight: 12,
    once: true,
    choices: [
      {
        id: "chase_new_rule",
        text: "立刻跟着新规则调整",
        effects: [
          stat("education", 7),
          stat("stress", 6),
          tag("rule_follower"),
          tag("world_policy_shift"),
          years(2),
        ],
      },
      {
        id: "miss_new_rule",
        text: "慢了一步，错过窗口",
        effects: [
          stat("education", -5),
          stat("mindset", -4),
          stat("luck", -3),
          tag("missed_policy_window"),
          tag("world_policy_shift"),
          years(2),
        ],
      },
    ],
  },
  {
    id: "adult_city_gate",
    stage: "adult",
    title: "城市的门",
    body: "你拖着行李站在大城市的出口。灯很亮，人很多，机会和房租一起张开嘴。",
    trigger: { minAge: 19, maxAge: 30 },
    weight: 30,
    once: true,
    milestone: true,
    choices: [
      {
        id: "enter_megacity",
        text: "留下来，挤进这座城",
        effects: [
          stat("career", 12),
          stat("wealth", -5),
          stat("stress", 8),
          tag("megacity_path"),
          tag("world_city_gate"),
          milestone("entered_megacity"),
          years(5),
        ],
      },
      {
        id: "return_hometown",
        text: "回去，先站稳脚跟",
        effects: [
          stat("family", 8),
          stat("wealth", 3),
          stat("career", 4),
          tag("hometown_return"),
          tag("world_hometown_gravity"),
          years(5),
        ],
      },
      {
        id: "float_between",
        text: "两边都不舍得，先漂着",
        effects: [
          stat("risk", 8),
          stat("mindset", 4),
          stat("relationships", -5),
          tag("floating_youth"),
          tag("world_departure_signal"),
          years(5),
        ],
      },
    ],
  },
  {
    id: "adult_first_job",
    stage: "adult",
    title: "第一份长期工作",
    body: "你拿到一份看起来稳定的工作。合同很薄，现实很厚。有人说这是开始，有人说这就是一辈子。",
    trigger: { minAge: 21, maxAge: 34 },
    weight: 26,
    once: true,
    choices: [
      {
        id: "steady_job",
        text: "接受稳定，把日子排好",
        effects: [
          stat("career", 14),
          stat("wealth", 8),
          stat("stress", 5),
          tag("steady_worker"),
          milestone("first_stable_job"),
          years(6),
        ],
      },
      {
        id: "jump_for_growth",
        text: "跳去更快的行业",
        effects: [
          stat("career", 10),
          stat("wealth", 4),
          stat("risk", 10),
          tag("growth_chaser"),
          tag("world_capital_wind"),
          years(6),
        ],
      },
    ],
  },
  {
    id: "adult_housing_tide",
    stage: "adult",
    title: "房价浪潮",
    body: "房价像潮水一样涨上来。你不买，像错过；你买，又像被套住。很多人的命运从一纸贷款开始转弯。",
    trigger: { minAge: 25, maxAge: 40 },
    weight: 22,
    once: true,
    choices: [
      {
        id: "take_mortgage",
        text: "咬牙上车",
        effects: [
          stat("wealth", 8),
          stat("stress", 14),
          stat("risk", 8),
          tag("mortgage_chain"),
          tag("world_housing_tide"),
          milestone("signed_mortgage"),
          years(6),
        ],
      },
      {
        id: "rent_and_wait",
        text: "继续租房，等一个更好的时机",
        effects: [
          stat("wealth", -3),
          stat("mindset", 5),
          stat("luck", 3),
          tag("missed_housing_tide"),
          tag("world_housing_tide"),
          years(6),
        ],
      },
    ],
  },
  {
    id: "adult_relationship_crossroad",
    stage: "adult",
    title: "亲密关系的账",
    body: "爱不是只在心里发生。它会落到城市、房子、父母、孩子、时间和钱上。",
    trigger: { minAge: 26, maxAge: 42 },
    weight: 20,
    once: true,
    choices: [
      {
        id: "build_family",
        text: "把两个人过成一家人",
        effects: [
          stat("family", 14),
          stat("relationships", 8),
          stat("stress", 6),
          tag("built_family"),
          tag("world_care_chain"),
          milestone("built_a_home"),
          years(7),
        ],
      },
      {
        id: "stay_single",
        text: "把人生先交还给自己",
        effects: [
          stat("mindset", 9),
          stat("career", 5),
          stat("family", -5),
          tag("self_kept"),
          years(7),
        ],
      },
    ],
  },
  {
    id: "adult_noble_person",
    stage: "adult",
    title: "贵人或偶然",
    body: "一个前辈在饭局上替你说了句话。你知道自己努力过，但也知道这句话不来，门就不会开。",
    trigger: {
      minAge: 24,
      maxAge: 42,
      conditions: [{ type: "stat", stat: "luck", op: ">=", value: 55 }],
    },
    weight: 14,
    once: true,
    choices: [
      {
        id: "accept_help",
        text: "接住这次顺风",
        effects: [
          stat("career", 14),
          stat("reputation", 8),
          stat("relationships", 5),
          tag("patron_found"),
          tag("world_capital_wind"),
          milestone("door_opened_by_another"),
          years(4),
        ],
      },
      {
        id: "refuse_favor",
        text: "不想欠这份人情",
        effects: [
          stat("mindset", 8),
          stat("career", 3),
          stat("relationships", -4),
          tag("clean_hands"),
          years(4),
        ],
      },
    ],
  },
  {
    id: "adult_startup_bet",
    stage: "adult",
    title: "创业局",
    body: "朋友说风口来了，再晚就没有位置。你看着存款和机会，忽然明白所谓逆天改命，多半先要把自己押上去。",
    trigger: { minAge: 26, maxAge: 38 },
    weight: 18,
    once: true,
    choices: [
      {
        id: "bet_on_startup",
        text: "押上几年，赌一次",
        effects: [
          stat("career", 12),
          stat("wealth", -10),
          stat("risk", 20),
          stat("reputation", 6),
          tag("risk_taker"),
          tag("world_capital_wind"),
          milestone("made_a_large_bet"),
          years(5),
        ],
      },
      {
        id: "keep_salary",
        text: "留在工资里慢慢攒",
        effects: [
          stat("wealth", 8),
          stat("career", 5),
          stat("risk", -3),
          tag("salary_anchor"),
          years(5),
        ],
      },
    ],
  },
  {
    id: "adult_ai_tide",
    stage: "adult",
    title: "新技术潮",
    body: "一场技术浪潮忽然越过行业边界。有人被托起，有人被替代。它不像命运，却比命运来得更快。",
    trigger: { minAge: 28, maxAge: 48 },
    weight: 18,
    once: true,
    choices: [
      {
        id: "learn_new_tool",
        text: "硬着头皮重新学习",
        effects: [
          stat("education", 8),
          stat("career", 10),
          stat("stress", 5),
          tag("adapted_to_ai"),
          tag("world_ai_tide"),
          years(4),
        ],
      },
      {
        id: "wait_it_out",
        text: "相信风会过去",
        effects: [
          stat("career", -6),
          stat("mindset", -3),
          stat("risk", 8),
          tag("missed_ai_tide"),
          tag("world_ai_tide"),
          years(4),
        ],
      },
    ],
  },
  {
    id: "adult_parent_illness",
    stage: "adult",
    title: "父母的病历",
    body: "一张病历把你从自己的计划里拽出来。你忽然发现，人生不是一条个人曲线，它还连着上一代的身体。",
    trigger: { minAge: 30, maxAge: 48 },
    weight: 16,
    once: true,
    choices: [
      {
        id: "become_caregiver",
        text: "把时间让给照护",
        effects: [
          stat("family", 14),
          stat("career", -6),
          stat("stress", 12),
          stat("wealth", -8),
          tag("caregiving_burden"),
          tag("world_care_chain"),
          years(5),
        ],
      },
      {
        id: "pay_for_care",
        text: "用钱换专业照护",
        effects: [
          stat("wealth", -14),
          stat("career", 4),
          stat("family", 5),
          tag("paid_for_care"),
          tag("world_care_chain"),
          years(5),
        ],
      },
    ],
  },
  {
    id: "adult_public_health_wave",
    stage: "adult",
    title: "公共健康风波",
    body: "城市忽然慢下来。办公室、医院、亲友群和新闻推送一起挤进生活。世界线不是背景，它会直接伸手推你。",
    trigger: { minAge: 25, maxAge: 55 },
    weight: 12,
    once: true,
    choices: [
      {
        id: "protect_family",
        text: "优先保护家人",
        effects: [
          stat("family", 8),
          stat("health", 5),
          stat("career", -4),
          stat("stress", 8),
          tag("family_first_crisis"),
          tag("world_health_wave"),
          years(3),
        ],
      },
      {
        id: "keep_working",
        text: "继续保住工作节奏",
        effects: [
          stat("career", 8),
          stat("health", -5),
          stat("stress", 10),
          tag("worked_through_crisis"),
          tag("world_health_wave"),
          years(3),
        ],
      },
    ],
  },
  {
    id: "middle_recession_notice",
    stage: "middle",
    title: "寒意通知",
    body: "公司群里发出一封措辞客气的邮件。时代不说自己冷，只让每个人回家数存款。",
    trigger: { minAge: 45, maxAge: 60 },
    weight: 22,
    once: true,
    choices: [
      {
        id: "accept_cut",
        text: "接受降薪，先活下来",
        effects: [
          stat("wealth", -8),
          stat("career", -4),
          stat("stress", 8),
          tag("survived_paycut"),
          tag("world_slow_recession"),
          years(4),
        ],
      },
      {
        id: "leave_company",
        text: "离开这条船",
        effects: [
          stat("career", -10),
          stat("risk", 10),
          stat("mindset", 6),
          tag("midlife_departure"),
          tag("world_slow_recession"),
          years(4),
        ],
      },
    ],
  },
  {
    id: "middle_body_warning",
    stage: "middle",
    title: "体检红字",
    body: "体检报告上出现几个红色箭头。你盯着它们，像盯着命运提前写好的批注。",
    trigger: { minAge: 42, maxAge: 64 },
    weight: 20,
    once: true,
    choices: [
      {
        id: "change_rhythm",
        text: "真正调整生活节奏",
        effects: [
          stat("health", 14),
          stat("stress", -8),
          stat("career", -4),
          tag("health_reckoning"),
          milestone("listened_to_the_body"),
          years(5),
        ],
      },
      {
        id: "ignore_warning",
        text: "先忙完这一阵再说",
        effects: [
          stat("health", -12),
          stat("career", 8),
          stat("stress", 10),
          tag("ignored_body_warning"),
          years(5),
        ],
      },
    ],
  },
  {
    id: "middle_child_or_legacy",
    stage: "middle",
    title: "下一代的门票",
    body: "如果你有孩子，教育像一场新的长跑；如果没有，你也会把某种期待投向后来的人。",
    trigger: { minAge: 42, maxAge: 60 },
    weight: 16,
    once: true,
    choices: [
      {
        id: "invest_next_generation",
        text: "把资源压到下一代",
        effects: [
          stat("wealth", -12),
          stat("family", 12),
          stat("stress", 6),
          tag("next_generation_bet"),
          tag("world_education_track"),
          years(5),
        ],
      },
      {
        id: "teach_without_owning",
        text: "把经验交给更年轻的人",
        effects: [
          stat("reputation", 8),
          stat("relationships", 8),
          stat("mindset", 6),
          tag("mentor_late_life"),
          years(5),
        ],
      },
    ],
  },
  {
    id: "middle_old_love_message",
    stage: "middle",
    title: "旧人来信",
    body: "多年未见的人发来消息。你们都绕了很远的路，才发现当年的遗憾没有消失，只是换了名字。",
    trigger: {
      minAge: 40,
      maxAge: 62,
      conditions: [{ type: "tag", tag: "unspoken_love", present: true }],
    },
    weight: 12,
    once: true,
    choices: [
      {
        id: "reply_gently",
        text: "温和地回信",
        effects: [
          stat("mindset", 8),
          stat("relationships", 4),
          tag("made_peace_with_youth"),
          milestone("answered_the_old_letter"),
          years(3),
        ],
      },
      {
        id: "leave_unread",
        text: "不再打开那扇门",
        effects: [
          stat("mindset", -3),
          stat("family", 4),
          tag("sealed_old_door"),
          years(3),
        ],
      },
    ],
  },
  {
    id: "middle_debt_returns",
    stage: "middle",
    title: "旧债回来",
    body: "年轻时欠下的账单，以另一种形式回来。它可能是钱，可能是关系，也可能是身体。",
    trigger: {
      minAge: 42,
      maxAge: 64,
      conditions: [{ type: "tag", tag: "world_family_debt", present: true }],
    },
    weight: 15,
    once: true,
    choices: [
      {
        id: "pay_old_debt",
        text: "一点点偿还",
        effects: [
          stat("wealth", -10),
          stat("family", 8),
          stat("mindset", 3),
          tag("debt_paid_in_middle_age"),
          milestone("old_debt_returned"),
          years(4),
        ],
      },
      {
        id: "roll_debt_forward",
        text: "把债往后推",
        effects: [
          stat("wealth", 4),
          stat("risk", 12),
          stat("stress", 10),
          tag("debt_rolled_forward"),
          years(4),
        ],
      },
    ],
  },
  {
    id: "middle_second_bloom",
    stage: "middle",
    title: "迟来的开花",
    body: "你以为一些门早已关上，直到某天，一个小机会从门缝里递进来。命运偶尔也会迟到。",
    trigger: {
      minAge: 45,
      maxAge: 64,
      conditions: [{ type: "stat", stat: "mindset", op: ">=", value: 62 }],
    },
    weight: 14,
    once: true,
    choices: [
      {
        id: "try_again",
        text: "再试一次",
        effects: [
          stat("career", 10),
          stat("reputation", 8),
          stat("stress", 4),
          tag("late_bloom"),
          milestone("bloomed_late"),
          years(5),
        ],
      },
      {
        id: "keep_small_happiness",
        text: "不追了，守住小日子",
        effects: [
          stat("mindset", 10),
          stat("family", 5),
          stat("health", 5),
          tag("small_happiness_kept"),
          years(5),
        ],
      },
    ],
  },
  {
    id: "elder_old_city",
    stage: "elder",
    title: "旧城拆迁",
    body: "你年轻时走过的街被围挡遮住。城市更新很快，记忆没有安置房。",
    trigger: { minAge: 65 },
    weight: 18,
    once: true,
    choices: [
      {
        id: "keep_photos",
        text: "把旧地方拍下来",
        effects: [
          stat("mindset", 5),
          stat("relationships", 3),
          tag("memory_keeper"),
          tag("world_old_city"),
          years(5),
        ],
      },
      {
        id: "do_not_return",
        text: "不再回头看",
        effects: [
          stat("mindset", -2),
          stat("health", 3),
          tag("cut_from_old_city"),
          tag("world_old_city"),
          years(5),
        ],
      },
    ],
  },
  {
    id: "elder_family_table",
    stage: "elder",
    title: "年夜饭的座位",
    body: "年夜饭桌上，有人缺席，有人新来。你突然明白，家族不是一棵树，而是一阵风吹过几代人的影子。",
    trigger: { minAge: 66 },
    weight: 20,
    once: true,
    choices: [
      {
        id: "speak_softly",
        text: "把话说软一点",
        effects: [
          stat("family", 9),
          stat("relationships", 7),
          stat("mindset", 5),
          tag("reconciled_elder"),
          milestone("softened_at_family_table"),
          years(6),
        ],
      },
      {
        id: "keep_old_rules",
        text: "还是按老规矩来",
        effects: [
          stat("family", -5),
          stat("reputation", 3),
          stat("mindset", -3),
          tag("old_rules_kept"),
          years(6),
        ],
      },
    ],
  },
  {
    id: "elder_apprentice",
    stage: "elder",
    title: "后来的人",
    body: "一个年轻人来问你当年怎么熬过来。你想了很久，发现能讲的不是成功，而是很多次没得选。",
    trigger: { minAge: 68 },
    weight: 16,
    once: true,
    choices: [
      {
        id: "tell_truth",
        text: "告诉他命运的重量",
        effects: [
          stat("reputation", 9),
          stat("relationships", 5),
          stat("mindset", 4),
          tag("legacy_keeper"),
          milestone("told_the_weight_of_fate"),
          years(6),
        ],
      },
      {
        id: "tell_hope",
        text: "只把希望讲给他听",
        effects: [
          stat("mindset", 6),
          stat("relationships", 6),
          stat("reputation", 4),
          tag("hope_teller"),
          years(6),
        ],
      },
    ],
  },
  {
    id: "elder_hospital_corridor",
    stage: "elder",
    title: "医院走廊",
    body: "医院走廊的灯永远很白。年轻时你以为身体由自己支配，老了才知道身体也是命的一部分。",
    trigger: { minAge: 70 },
    weight: 14,
    once: true,
    choices: [
      {
        id: "accept_treatment",
        text: "认真治疗，慢慢走",
        effects: [
          stat("health", 8),
          stat("wealth", -8),
          stat("mindset", 3),
          tag("accepted_aging"),
          years(6),
        ],
      },
      {
        id: "refuse_tubes",
        text: "不想把最后交给管子",
        effects: [
          stat("health", -10),
          stat("mindset", 8),
          stat("family", -4),
          tag("chose_dignity_over_length"),
          years(6),
        ],
      },
    ],
  },
  {
    id: "hidden_fate_motto",
    stage: "elder",
    title: "纸背的话",
    body: "你在一本旧册子的纸背看见一行很淡的字：万般都是命，半点不由人。年轻时你会觉得这像认输，到了这一刻才知道，它说的是那些早已压在每个人身上的重量。",
    trigger: {
      minAge: 72,
      maxAge: 89,
      conditions: [
        { type: "tag", tag: "legacy_keeper", present: true },
        { type: "tag", tag: "reconciled_elder", present: true },
      ],
    },
    weight: 28,
    once: true,
    hidden: true,
    choices: [
      {
        id: "fold_the_line_back",
        text: "把这句话重新夹回纸背",
        effects: [
          stat("mindset", 6),
          stat("reputation", 2),
          tag("hidden_fate_line_found"),
          milestone("read_the_hidden_fate_line"),
          years(1),
        ],
      },
    ],
  },
  {
    id: "fate_lucky_break",
    stage: "any",
    title: "命里的偏财",
    body: "一笔意外的钱落到你手里，不多不少，刚好能让某个困局松动。你很难说这是选择，还是命数。",
    trigger: {
      minAge: 20,
      maxAge: 70,
      conditions: [{ type: "stat", stat: "luck", op: ">=", value: 66 }],
    },
    weight: 8,
    once: true,
    choices: [
      {
        id: "save_windfall",
        text: "存起来，给未来留余地",
        effects: [
          stat("wealth", 14),
          stat("risk", -6),
          tag("windfall_saved"),
          milestone("luck_arrived_as_money"),
          years(2),
        ],
      },
      {
        id: "spend_windfall",
        text: "花掉它，换一口气",
        effects: [
          stat("mindset", 9),
          stat("wealth", 4),
          stat("relationships", 3),
          tag("windfall_spent"),
          years(2),
        ],
      },
    ],
  },
  {
    id: "fate_low_luck_misstep",
    stage: "any",
    title: "差一步",
    body: "你几乎赶上了那趟车、那个窗口、那份名单。可命运常常不需要把门关死，只要让你晚到一点。",
    trigger: {
      minAge: 18,
      maxAge: 70,
      conditions: [{ type: "stat", stat: "luck", op: "<=", value: 34 }],
    },
    weight: 8,
    once: true,
    choices: [
      {
        id: "swallow_miss",
        text: "把错过咽下去",
        effects: [
          stat("mindset", -5),
          stat("stress", 6),
          tag("fateful_miss"),
          milestone("missed_by_one_step"),
          years(2),
        ],
      },
      {
        id: "rage_against_miss",
        text: "不服，硬闯另一扇门",
        effects: [
          stat("risk", 10),
          stat("career", 4),
          stat("stress", 8),
          tag("fought_miss"),
          years(2),
        ],
      },
    ],
  },
  {
    id: "risk_accident",
    stage: "any",
    title: "横祸",
    body: "有些事没有预兆。前一秒你还在盘算明天，后一秒命运已经换了语气。",
    trigger: {
      minAge: 20,
      conditions: [{ type: "stat", stat: "risk", op: ">=", value: 82 }],
    },
    weight: 10,
    once: true,
    choices: [
      {
        id: "step_back_from_edge",
        text: "临门收手",
        effects: [
          stat("risk", -25),
          stat("mindset", 3),
          tag("stepped_back_from_edge"),
          years(2),
        ],
      },
      {
        id: "one_more_bet",
        text: "再赌一次",
        effects: [tag("last_bet"), end("accident")],
      },
    ],
  },
  {
    id: "health_collapse_event",
    stage: "any",
    title: "身体讨债",
    body: "身体终于来讨旧账。那些你以为能熬过去的夜晚，都排着队回来。",
    trigger: {
      minAge: 35,
      conditions: [{ type: "stat", stat: "health", op: "<=", value: 18 }],
    },
    weight: 10,
    once: true,
    choices: [
      {
        id: "full_stop_recovery",
        text: "停下来，全力恢复",
        effects: [
          stat("health", 20),
          stat("career", -8),
          stat("wealth", -12),
          tag("survived_body_debt"),
          years(4),
        ],
      },
      {
        id: "body_breaks",
        text: "这次撑不过去了",
        effects: [tag("body_debt_collected"), end("health_collapse")],
      },
    ],
  },
  ...everydayLifeEvents,
  ...wealthTimelineEvents,
  ...annualFallbackEvents,
  {
    id: "ordinary_years",
    stage: "any",
    title: "平常的一年",
    body: "没有戏剧性的转折。日子像水一样从指缝里过去，可水也会慢慢改河道。命数不总是轰然落下，有时只是把这一年悄悄垫在脚下。",
    weight: 1,
    fallback: true,
    choices: [
      {
        id: "let_time_pass",
        text: "顺着命数往前走",
        effects: [
          stat("health", -2),
          stat("stress", 1),
          stat("mindset", 1),
          tag("ordinary_years_accumulated"),
          years(3),
        ],
      },
    ],
  },
];
