import type { LifeEvent } from "../../engine/types";

export const baseEvents: LifeEvent[] = [
  {
    id: "birth_background",
    stage: "baby",
    title: "出生背景",
    body: "你降生在一个普通城市。家庭资源、照料方式和早期安全感，开始悄悄改变你之后的人生。",
    trigger: { minAge: 0, maxAge: 2 },
    weight: 100,
    once: true,
    milestone: true,
    choices: [
      {
        id: "stable_family",
        text: "在稳定照料中长大",
        effects: [
          { type: "stat", stat: "family", delta: 8 },
          { type: "stat", stat: "mindset", delta: 5 },
          { type: "stat", stat: "classBackground", delta: 6 },
          { type: "tag", tag: "supportive_family", action: "add" },
          { type: "milestone", milestone: "early_security" },
          { type: "advanceTime", years: 4 },
        ],
      },
      {
        id: "restless_start",
        text: "在频繁变化中适应环境",
        effects: [
          { type: "stat", stat: "luck", delta: 5 },
          { type: "stat", stat: "stress", delta: 8 },
          { type: "stat", stat: "relationships", delta: -4 },
          { type: "tag", tag: "early_pressure", action: "add" },
          { type: "advanceTime", years: 4 },
        ],
      },
    ],
  },
  {
    id: "childhood_spark",
    stage: "child",
    title: "童年的兴趣",
    body: "你开始对世界产生稳定的好奇心。大人们说这只是小孩的兴趣，但你能感觉到它正在塑造你的注意力。",
    trigger: { minAge: 3, maxAge: 12 },
    weight: 30,
    once: true,
    choices: [
      {
        id: "read_books",
        text: "把时间花在阅读和观察上",
        effects: [
          { type: "stat", stat: "intelligence", delta: 8 },
          { type: "stat", stat: "education", delta: 10 },
          { type: "stat", stat: "relationships", delta: -2 },
          { type: "tag", tag: "bookish_child", action: "add" },
          { type: "advanceTime", years: 6 },
        ],
      },
      {
        id: "make_friends",
        text: "和同龄人一起玩到天黑",
        effects: [
          { type: "stat", stat: "charm", delta: 6 },
          { type: "stat", stat: "relationships", delta: 8 },
          { type: "stat", stat: "education", delta: 3 },
          { type: "tag", tag: "social_child", action: "add" },
          { type: "advanceTime", years: 6 },
        ],
      },
      {
        id: "sports_field",
        text: "在运动场上消耗精力",
        effects: [
          { type: "stat", stat: "health", delta: 8 },
          { type: "stat", stat: "mindset", delta: 4 },
          { type: "stat", stat: "education", delta: 2 },
          { type: "advanceTime", years: 6 },
        ],
      },
    ],
  },
  {
    id: "childhood_family_shift",
    stage: "child",
    title: "家庭气候变化",
    body: "家里的经济与关系状态出现起伏。你第一次意识到，家庭并不是一个完全稳定的背景。",
    trigger: { minAge: 8, maxAge: 12 },
    weight: 18,
    once: true,
    choices: [
      {
        id: "stay_quiet",
        text: "把感受藏起来，专注自己的事",
        effects: [
          { type: "stat", stat: "stress", delta: 8 },
          { type: "stat", stat: "education", delta: 5 },
          { type: "stat", stat: "family", delta: -4 },
          { type: "advanceTime", years: 3 },
        ],
      },
      {
        id: "talk_with_family",
        text: "尝试和家人认真沟通",
        effects: [
          { type: "stat", stat: "family", delta: 7 },
          { type: "stat", stat: "mindset", delta: 4 },
          { type: "stat", stat: "stress", delta: -3 },
          { type: "advanceTime", years: 3 },
        ],
      },
    ],
  },
  {
    id: "teen_exam_pressure",
    stage: "teen",
    title: "升学压力",
    body: "考试、排名、期待和比较一起涌来。你需要决定自己如何面对这段密集的竞争。",
    trigger: { minAge: 13, maxAge: 18 },
    weight: 35,
    once: true,
    milestone: true,
    choices: [
      {
        id: "study_harder",
        text: "拼命学习，先把路铺出来",
        effects: [
          { type: "stat", stat: "education", delta: 16 },
          { type: "stat", stat: "stress", delta: 10 },
          { type: "stat", stat: "health", delta: -4 },
          { type: "tag", tag: "exam_focused", action: "add" },
          { type: "milestone", milestone: "survived_exam_pressure" },
          { type: "advanceTime", years: 5 },
        ],
      },
      {
        id: "balanced_growth",
        text: "保持节奏，也保留生活",
        effects: [
          { type: "stat", stat: "education", delta: 8 },
          { type: "stat", stat: "mindset", delta: 6 },
          { type: "stat", stat: "relationships", delta: 4 },
          { type: "advanceTime", years: 5 },
        ],
      },
      {
        id: "reject_grind",
        text: "不想被单一标准定义",
        effects: [
          { type: "stat", stat: "mindset", delta: 10 },
          { type: "stat", stat: "education", delta: -2 },
          { type: "stat", stat: "charm", delta: 6 },
          { type: "tag", tag: "independent_teen", action: "add" },
          { type: "advanceTime", years: 5 },
        ],
      },
    ],
  },
  {
    id: "adult_first_path",
    stage: "adult",
    title: "成年后的第一条路",
    body: "你离开熟悉的环境，开始为自己的生活负责。学历、工作、城市和人际圈同时发生变化。",
    trigger: { minAge: 19, maxAge: 32 },
    weight: 35,
    once: true,
    milestone: true,
    choices: [
      {
        id: "professional_track",
        text: "进入稳定职业路径",
        effects: [
          { type: "stat", stat: "career", delta: 18 },
          { type: "stat", stat: "wealth", delta: 10 },
          { type: "stat", stat: "stress", delta: 6 },
          { type: "milestone", milestone: "first_career_path" },
          { type: "advanceTime", years: 10 },
        ],
      },
      {
        id: "continue_study",
        text: "继续深造，延迟进入社会",
        effects: [
          { type: "stat", stat: "education", delta: 18 },
          { type: "stat", stat: "wealth", delta: -8 },
          { type: "stat", stat: "reputation", delta: 5 },
          { type: "tag", tag: "advanced_study", action: "add" },
          { type: "advanceTime", years: 10 },
        ],
      },
      {
        id: "startup_attempt",
        text: "尝试创业或自由职业",
        effects: [
          { type: "stat", stat: "career", delta: 10 },
          { type: "stat", stat: "wealth", delta: -6 },
          { type: "stat", stat: "risk", delta: 18 },
          { type: "stat", stat: "reputation", delta: 8 },
          { type: "tag", tag: "risk_taker", action: "add" },
          { type: "advanceTime", years: 10 },
        ],
      },
    ],
  },
  {
    id: "adult_relationships",
    stage: "adult",
    title: "亲密关系的选择",
    body: "亲密关系不再只是心动，它牵动时间、责任、边界和未来规划。",
    trigger: { minAge: 25, maxAge: 44 },
    weight: 22,
    once: true,
    choices: [
      {
        id: "build_family",
        text: "认真经营稳定关系",
        effects: [
          { type: "stat", stat: "family", delta: 12 },
          { type: "stat", stat: "relationships", delta: 8 },
          { type: "stat", stat: "stress", delta: 5 },
          { type: "tag", tag: "built_family", action: "add" },
          { type: "advanceTime", years: 10 },
        ],
      },
      {
        id: "protect_independence",
        text: "优先保留独立生活",
        effects: [
          { type: "stat", stat: "mindset", delta: 8 },
          { type: "stat", stat: "career", delta: 6 },
          { type: "stat", stat: "relationships", delta: -4 },
          { type: "advanceTime", years: 10 },
        ],
      },
    ],
  },
  {
    id: "middle_balance",
    stage: "middle",
    title: "中年的再平衡",
    body: "你已经积累了一些成果，也背上了一些负担。时间变得更贵，取舍也更具体。",
    trigger: { minAge: 45, maxAge: 64 },
    weight: 30,
    once: true,
    milestone: true,
    choices: [
      {
        id: "health_first",
        text: "把健康和节奏放回第一位",
        effects: [
          { type: "stat", stat: "health", delta: 14 },
          { type: "stat", stat: "stress", delta: -10 },
          { type: "stat", stat: "career", delta: -3 },
          { type: "milestone", milestone: "midlife_rebalance" },
          { type: "advanceTime", years: 14 },
        ],
      },
      {
        id: "push_career",
        text: "抓住最后一轮事业上升期",
        effects: [
          { type: "stat", stat: "career", delta: 16 },
          { type: "stat", stat: "wealth", delta: 14 },
          { type: "stat", stat: "stress", delta: 12 },
          { type: "stat", stat: "reputation", delta: 8 },
          { type: "advanceTime", years: 14 },
        ],
      },
      {
        id: "repair_bonds",
        text: "修复被忽视的关系",
        effects: [
          { type: "stat", stat: "family", delta: 12 },
          { type: "stat", stat: "relationships", delta: 10 },
          { type: "stat", stat: "mindset", delta: 5 },
          { type: "advanceTime", years: 14 },
        ],
      },
    ],
  },
  {
    id: "elder_reflection",
    stage: "elder",
    title: "老年的回望",
    body: "你开始频繁回望这一生。曾经重要的胜负逐渐退后，留下的是关系、身体和自我评价。",
    trigger: { minAge: 65 },
    weight: 35,
    once: true,
    milestone: true,
    choices: [
      {
        id: "share_experience",
        text: "把经验讲给后来的人",
        effects: [
          { type: "stat", stat: "reputation", delta: 8 },
          { type: "stat", stat: "relationships", delta: 6 },
          { type: "stat", stat: "mindset", delta: 5 },
          { type: "advanceTime", years: 18 },
        ],
      },
      {
        id: "quiet_life",
        text: "过安静、规律的小日子",
        effects: [
          { type: "stat", stat: "health", delta: 6 },
          { type: "stat", stat: "stress", delta: -8 },
          { type: "stat", stat: "family", delta: 4 },
          { type: "advanceTime", years: 18 },
        ],
      },
    ],
  },
  {
    id: "serious_health_crisis",
    stage: "any",
    title: "严重健康危机",
    body: "长期透支终于要求你付出代价。你被迫面对身体发出的警报。",
    trigger: {
      minAge: 35,
      conditions: [{ type: "stat", stat: "health", op: "<=", value: 22 }],
    },
    weight: 8,
    once: true,
    choices: [
      {
        id: "emergency_recovery",
        text: "全力治疗和调整生活",
        effects: [
          { type: "stat", stat: "health", delta: 18 },
          { type: "stat", stat: "wealth", delta: -16 },
          { type: "stat", stat: "stress", delta: -8 },
          { type: "advanceTime", years: 4 },
        ],
      },
      {
        id: "collapse",
        text: "已经来不及了",
        effects: [{ type: "triggerEnding", endingId: "health_collapse" }],
      },
    ],
  },
  {
    id: "high_risk_accident",
    stage: "any",
    title: "高风险意外",
    body: "连续的冒险选择让你站在危险边缘。运气不一定永远站在你这边。",
    trigger: {
      minAge: 20,
      conditions: [{ type: "stat", stat: "risk", op: ">=", value: 80 }],
    },
    weight: 6,
    once: true,
    choices: [
      {
        id: "take_the_risk",
        text: "继续冒险",
        effects: [{ type: "triggerEnding", endingId: "accident" }],
      },
      {
        id: "step_back",
        text: "及时收手",
        effects: [
          { type: "stat", stat: "risk", delta: -25 },
          { type: "stat", stat: "mindset", delta: 4 },
          { type: "advanceTime", years: 2 },
        ],
      },
    ],
  },
  {
    id: "ordinary_years",
    stage: "any",
    title: "平常的几年",
    body: "没有戏剧性的转折。生活由许多相似的日子堆叠起来，慢慢改变你的身体、关系和心境。",
    weight: 1,
    fallback: true,
    choices: [
      {
        id: "let_time_pass",
        text: "顺着日子往前走",
        effects: [
          { type: "stat", stat: "health", delta: -2 },
          { type: "stat", stat: "stress", delta: 1 },
          { type: "stat", stat: "mindset", delta: 1 },
          { type: "advanceTime", years: 3 },
        ],
      },
    ],
  },
];
